header:
  license:
    text: |
      Copyright © 2023-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
      Dell Technologies, Dell, EMC, Dell EMC and other trademarks are trademarks of Dell Inc. or its subsidiaries.
      Other trademarks may be trademarks of their respective owners.
  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '.github'
  comment: on-failure
