header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Dell Technologies
    content: 
        Copyright © 2023-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
        Dell Technologies, Dell, EMC, Dell EMC and other trademarks are trademarks of Dell Inc. or its subsidiaries.
        Other trademarks may be trademarks of their respective owners.
    pattern: 
        Copyright © 2023-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
        Dell Technologies, Dell, EMC, Dell EMC and other trademarks are trademarks of Dell Inc. or its subsidiaries.
        Other trademarks may be trademarks of their respective owners.
  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '.github'
    - '.gitignore'
    - 'go.mod'
    - 'go.sum'
    - '.licenserc.yaml'
    - '.git'
  comment: on-failure
  dependency:
    files:
      - go.mod            # If this is a Go project.
