# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

name: Replace External GitHub Domain
description: Replaces https://github.com/dell/ with the internal Enterprise domain in files.

runs:
  using: "composite"
  steps:
    - name: Run domain replacement script
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/replace.sh
        ${{ github.action_path }}/replace.sh "${{ inputs.file-glob }}"
        