# Copyright (c) 2020-2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
name: 'Go Tester'
description: 'Runs unit tests and verifies code coverage per package'
inputs:
  threshold:
    description: 'Code coverage threshold for packages'
    required: true
    default: "90"
  test-folder:
    description: 'Folder the test is run in'
    required: false
    default: "."
  skip-list:
    description: 'A comma delimited list of pkg names to skip for coverage constraint'
    required: false
    default: ""
  race-detector:
    description: 'Boolean to enable the race detector'
    required: false
    default: "true"
  skip-test:
    description: 'Regex for skipping tests'
    required: false
    default: ""
  run-test:
    description: 'Regex to specify tests to run'
    required: false
    default: ""
  exclude-directory:
    description: 'Name of directory to be excluded from go test'
    required: false
    default: ""
outputs:
  coverage:
    description: 'A summary of the code coverage results meeting the threshold'
  code_coverage_artifact:
    description: 'The code coverage report for pull requests'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.threshold }}
    - ${{ inputs.test-folder }}
    - ${{ inputs.skip-list }}
    - ${{ inputs.race-detector }}
    - ${{ inputs.skip-test }}
    - ${{ inputs.run-test }}
    - ${{ inputs.exclude-directory }}
branding:
  icon: 'shield'
  color: 'blue'
