# Copyright (c) 2020 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
name: 'Go Tester'
description: 'Runs unit tests and verifies code coverage per package'
inputs:
  threshold:
    description: 'Code coverage threshold for packages'
    required: true
    default: 90
  test-folder:
    description: 'Folder the test is run in'
    required: true
    default: "."
  skip-list:
    description: 'A comma delimited list of pkg names to skip for coverage constraint'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.threshold }}
    - ${{ inputs.test-folder }}
    - ${{ inputs.skip-list }}
branding:
  icon: 'shield'
  color: 'blue'
