# Copyright (c) 2020 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
name: 'Check Formatting, Linting, Vetting'
description: 'Runs gofmt, golint, and go vet'

inputs:
  directories:
    description: >
      Directories to run checks. Format is:
        directories: [--vet-in-dir <VET_DIR>] <DIRS>
      As shown, you can optionally specify '--vet-in-dir' for cases where the module is
      defined within a specific directory and you would like to run the 'go vet' there.
    required: true
    default: './...'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directories }}

branding:
  icon: 'shield'
  color: 'blue'
