# Copyright (c) 2020 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
name: 'Code Sanitizer'
description: 'Checks for forbidden words and text in the code'
author: 'ameer-jabbar'

inputs:
  args:
    description: 'Path to check'
    required: true
    default: '.'

runs:
    using: 'docker'    
    image: 'Dockerfile'
    args:
      - ${{ inputs.args }}

branding:
  icon: 'shield'
  color: 'blue'
