---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "saturday"
    groups:
      github-actions:
        patterns:
          - "*"

  # go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "00:00"
    groups:
      goclient-libraries:
        patterns:
          - "github.com/dell/goscaleio"
          - "github.com/dell/gopowermax"
          - "github.com/dell/gounity"
          - "github.com/dell/gopowerscale"
          - "github.com/dell/gopowerstore"
          - "github.com/dell/gobrick"
          - "github.com/dell/gocsi"
          - "github.com/dell/goiscsi"
          - "github.com/dell/gonvme"
          - "github.com/dell/goobjectscale"
          - "github.com/dell/gofsutil"
          - "github.com/dell/dell-csi-extensions"
          - "github.com/dell/connectivity-cert-persister-k8s"
          - "github.com/dell/csi-metadata-retriever"
          - "github.com/dell/csi-volumegroup-snapshotter"
      third-party-dependencies:
        patterns:
          - "*"
