name: 'Check GO security'
description: 'Runs gosec'

inputs:
  args:
    description: 'Arguments for gosec'
    required: true
    default: '-h'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}

branding:
  icon: 'shield'
  color: 'blue'
