# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Reusable workflow to perform release activities on Golang based projects
name: Release

# Invocable as a reusable workflow
on:
  workflow_call:

# Various jobs
jobs:
    go-build:
      name: Test repository builds

    build-and-scan:
      name: Build and Scan Images

    security-scan:
      name: Security Scans
      runs-on: ubuntu-latest

    release-branch:
      name: Create Release Branch
      runs-on: ubuntu-latest

    release:
      name: Create Release
          -