# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Reusable workflow to perform release activities on Golang based projects
name: Release

# Invocable as a reusable workflow
on:
  workflow_call:

# Various jobs
jobs:
    release-version:
      name: Update Release Version
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v4
        - name: Update release version references
          # grep for version references
          # create var with new version by incrementing the current version by 1
          # update version references
          # commit changes
          # push changes

    # only run after release-version PR is merged
    # implement step
    go-build:
      name: Test Repository Build

    # implement step
    build-and-scan:
      name: Build and Scan Images

    # implement step
    security-scan:
      name: Security Scans
      runs-on: ubuntu-latest

    # implement step
    release-branch:
      name: Create Release Branch
      runs-on: ubuntu-latest

    # implement step
    release:
      name: Create Release
      runs-on: ubuntu-latest